# site settings
title: Aninoy Mahapatra
subtitle: Personal website for Aninoy Mahapatra
email: aninoy@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Aninoy Mahaptra
street_address:
city: Los Angeles
state: CA
zip_code:
country: United States of America
phone: (213) 268-9683

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/aninoy
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/aninoy
pinterest_url:
slack_url:
twitter_url: https://twitter.com/aninoy

# build settings
markdown: kramdown

sass:
  style: compressed
