# site settings
title: Aninoy Mahapatra
subtitle:
email: aninoy@gmail.com
description: I create end-to-end web applications and data pipelines
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://www.aninoy.com" # the base hostname & protocol for your site
author: Aninoy Mahapatra
street_address:
city: Los Angeles
state: CA
zip_code:
country: United States of America
phone: (213) 268-9683

# homepage tiles
tiles-source: projects # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/aninoy
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/aninoy
pinterest_url:
slack_url:
twitter_url: https://twitter.com/aninoy

# build settings
markdown: kramdown

# collection settings
collections:
    projects:
        output: true
sass:
  style: compressed
